### ISSUE TITLE
Uses Node 6 execution handler will be removed March 31st 2022

### ISSUE THREAD

**Issue by iloabn** [jycouet/VSTSExtensions#48]
**Describe the bug**
When running the Renovate Me extension (extension 0.4.1, task 0.2.0) I get the following error from Azure DevOps:

> This task uses Node 6 execution handler, which will be removed March 31st 2022. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10 (check this page also if you would like to disable Node 6 deprecation warnings). If you are the user - feel free to reach out to the owners of this task to proceed on migration.

**To Reproduce**
1. Start a pipeline that uses the Renovate Me extension
2. Let it run to completion
3. Open the logs for the Renovate Me and notice the warning on line 9

**Expected behavior**
No warning.

**Screenshots**
![image](https://user-images.githubusercontent.com/5629868/144013396-e586ea66-9f14-4187-bcfd-d3b2aa6c103c.png)

**Additional context**
I'd gladly try to create a PR myself to fix this issue. But I first wanted to check if that's encouraged and/or if this is something you're already working on?

**Comment by jycouet** [comment]
Hello, 
Thank you for the info.
As I'm not using Azure atm, I was not aware.

It would be great to do a big package update anyway 👍 

I'll see when I have time.
Do not hesitate to remind me if it's taking to long.

**Comment by iloabn** [comment]
Thanks for the quick update. Please do let me know if there's anything I can do to help @jycouet. As I said, if it would be of help to you, I could for example try to get a branch started for this.
I also have active code in multiple Azure organisations and I'm admin in one of them so could install work-in-progress packages if that would help.

**Comment by sommmen** [comment]
Hiya also watching this. Taking a quick look and just updating all packages and this should run just fine - i'm no node user however.

@jycouet (or @iloabn ;) ) let me know if you have some time in the next couple months to fix the issue before the task would break due to the deprecation issue. I'm thinking about using either Renovate or Dependabot but if this task will break in march that does not become much of an option.

Also AFAIK you can just create a personal account and get 1800 free build minutes and test with that:
https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/ so i dont think you'd need a trial account?

**Comment by jycouet** [comment]
I just published a new version `0.7.1` could you check please?
Re open the issue if it's not better.

**Comment by sommmen** [comment]
> I just published a new version `0.7.1` could you check please? Re open the issue if it's not better.

Hiya,

Instead of this ms build task i decided to drop it, and follow this guide instead:
https://blog.objektkultur.de/how-to-setup-renovate-in-azure-devops/

This task used to be mentioned in the docs of renovate but i could not find it and now the docs are like this:
https://docs.renovatebot.com/setup-azure-devops/

I.e. this task seems to be kinda obsolete - the config seems really easy.

**Comment by jycouet** [comment]
Thank you for the update.

_For info, this package is mentioned [here](https://github.com/renovatebot/renovate/blob/81090406ca101bd07ac23f4988c8906ab265a1f7/readme.md#renovate-me-extension)_

The guide seems to do the same thing as my task. 
Good that it's easy to use renovate without my package 👍
